### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by pfefferle** [pfefferle/mycroft-mark2-wyoming-satellite#1]
@synesthesiam I would love to get your feedback on this!

**Comment by synesthesiam** [comment]
This looks great! I will have to give it a try on my Mark II.

Someday, I need to update the [mark-ii-sandbox](https://github.com/MycroftAI/mark-ii-sandbox) to Debian Bookworm.
With some small tweak, an image with the Wyoming satellite software baked in could be created :slightly_smiling_face:

**Comment by pfefferle** [comment]
@synesthesiam thanks a lot for taking your time and having a look! A dedicated image would be awesome!

I also experimented a bit with an xserver to load home assistant on the screen! Will also add that to the doc.

**Comment by pfefferle** [comment]
@synesthesiam I tried to build a new image, but img2tar.py seem to no longer work properly. The result of `get_mountpoints` does no longer show `# MountPoints:        /media/XXX/YYY`. Can you maybe support me a bit, so that I can try to build a newer image?

I have not much experience with images yet :(

**Comment by super-qua** [comment]
@pfefferle I was able to build the image after adding a `udisksctl mount` with the same parameters right before the `udisksctl info` in `getMountpoints()` in img2tar.py.

but no warranties from my side if this is correct, because, frankly, I have no clue what I was doing there.
just saw that the info output did not show any mount points and thought that might help. 

most probably a `unmount` is required as well.

**Comment by pfefferle** [comment]
I gave up on that project to be honest. The hardware was quite expensive and it never worked properly, so I decided to sell my Mark II and the DevKit 😔

But thanks for your feedback @super-qua !

**Comment by synesthesiam** [comment]
Sorry this didn't work out @pfefferle. I haven't had any time to try and get my Mark II's working again 🫤

**Comment by pfefferle** [comment]
@synesthesiam no problem :)

I think even if you had the time to work on something, the community that uses a Mark II and Home Assistant is so small, so that it might never really be actively maintained.

I am looking forward to what Nabu Casa/Home Assistant is planning to release by the end of the year.

...and the DevKit is not yet sold, so maybe... ;)

**Comment by super-qua** [comment]
I'd like to activate mine again and see if I can get it to work as a basic Wyoming satellite with a kiosk mode HA and some basic features like the led ring working on wake word detection. 
but don't have much time for it either. we'll see how far I get. 
if there is any progress I'll make sure to share it.

**Comment by pfefferle** [comment]
@super-qua Awesome! I am curious about your progress!

**Comment by super-qua** [comment]
@pfefferle I was about to publish the guide on how to set everything up, when I stumbled across https://community.openconversational.ai/t/sj-201-sj201-failure-mechanism-identified/15299.
now I think I am honestly at the point of giving up on the device. I am thinking about replacing the SJ-201 with a mic hat, but my motivation is very low at this point.

**Comment by synesthesiam** [comment]
That's unfortunate to hear. I guess it may not be worth trying to keep the Mark II's going ☹️

**Comment by pfefferle** [comment]
I've sold both now :)
